version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sipentest/php
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

    networks:
      - app-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4.21
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sipentest
      MYSQL_USER: uroot
      MYSQL_PASSWORD: uroot
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data: